---
title: "BAI avgs"
author: "Gabby John"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(treenetproc, `force = TRUE`)
library(ggplot2)

avgBAIgro_yr <- read.csv("~/research/avgBAIgro_yr.csv",stringsAsFactors = TRUE)
avgBAIgro_yr$avggro_yr<-as.numeric(as.character(avgBAIgro_yr$avggro_yr))
```

```{r}
#First grab years string
years <-left(avgBAIgro_yr[,"ts"],4)

par(mfrow=c(1,1))
#Then set margins 
par(mar = c(5, 5, 5, 5))

for(y in 1:length(unique(years))){
#Now we can select years
sel<-avgBAIgro_yr[which(years==unique(years)[y]),]
#But we need to handle first year first
if(y==1){
   plot(difftime(as.POSIXct(sel$ts,format="%Y-%m-%d %H:%M:%S",tz="GMT"),
  as.POSIXct(paste0(unique(years)[y],"-01-01 00:00:00"),
                  format="%Y-%m-%d %H:%M:%S",tz="GMT"),
                  units = "days"),
         sel$avggro_yr,
         ylab="AVG Cumulative BAI",
         xlab="Day of year",type="l",
         col=rainbow(length(unique(years)))[y],pch=16,
         xlim=c(90,300),
         ylim=c(min(avgBAIgro_yr$avggro_yr,na.rm=T),
                max(avgBAIgro_yr$avggro_yr,na.rm=T)),
         main="AVG BAI Cleaned")
    
    legend("topleft",
           as.character(unique(avgBAIgro_yr$yr)),
           col=rainbow(length(unique(avgBAIgro_yr$yr))),
           bty="n",pch=16)
# Now we can add other years
  }else{
    lines(difftime(as.POSIXct(sel$ts,format="%Y-%m-%d %H:%M:%S",tz="GMT"),
                   as.POSIXct(paste0(unique(years)[y],"-01-01 00:00:00"),
                              format="%Y-%m-%d %H:%M:%S",tz="GMT"),
                   units = "days"),
          sel$avggro_yr,
          col=rainbow(length(unique(years)))[y],pch=16)}
}
```